### ISSUE TITLE
give wc_lang Reader access to obj_model Reader keyword parameters

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_lang#12] opened 2018-04-19 13:35 UTC
Simply pass kwargs from wc_lang.io.Reader().run() to obj_model.io.Reader().run()
Useful, e.g., when a model and wc_lang are out of synch and want to want to use one of the ignore_* args

**Comment by jonrkarr** [comment] 2018-04-19 13:45
Duplicate of #11

**Closed by jonrkarr** 2018-04-19 13:45 UTC
